apache/rocketmq-client-python

- src/PythonWrapper.cpp
- src/PythonWrapper.h
we can set a namesrv domain when init a producer, push comsumer or pull comsumer
> support namesrv domain in producer and consumer

- .gitignore
- doc/Introduction.md
- doc/api-doc/consumer-push.md
- sample/testConsumer.py
- src/PythonWrapper.cpp
- src/PythonWrapper.h
- test/TestConsumeMessages.py
fixed #18: deadlock when call PyDestroyPushConsumer; add args field for python callback.
> Fixed deadlock, and add args field for python callback.

- CMakeLists.txt
- project/CMakeLists.txt
> Support macOS Mojave 10.14.2

- doc/Introduction.md
> Update Introduction for macOS

- .travis.yml
- README.md
1. enable Travis CI 
2. add Travis CI lable
> Enable Travis CI 

- .travis.yml
Polish Travis: download CPP core from OSS US region.
> Polish Travis:download CPP core from oss us region.

- doc/Introduction.md
fix command error
fix command error
fix command error
XXXX
> fix command error

- src/PythonWrapper.cpp
- src/PythonWrapper.h
- test/TestConsumeMessages.py
- test/TestSendMessages.py
(1) add batch message support
(2) add orderly consume support
(3) add broadcast consume support
XX
XXXX
> add batch message support, orderly consume support and broadcast consume support

- .travis.yml
- rocketmq/client.py
- tests/test_consumer.py
- tests/test_producer.py
`docker build --cache-from` seems not working properly.
> Do not build librocketmq.so on CI

- rocketmq/client.py
fix the issue that cannot set [group](https://github.com/apache/rocketmq-client-python/issues/58).
XX
XXXX
> fix(client) fix set group issue

- .bumpversion.cfg
- README.md
- changelog
- ci/Dockerfile
- dev-requirements.txt
- manylinux.sh
- pytest.ini
- rocketmq/__init__.py
- rocketmq/client.py
- rocketmq/consts.py
- rocketmq/exceptions.py
- rocketmq/ffi.py
- setup.cfg
- setup.py
- tests/conftest.py
- tests/test_consumer.py
- tests/test_producer.py
for https://github.com/apache/rocketmq-client-python/issues/59
XX
XXXX
> style(client) add apache 2 license header to source file

- src/PythonWrapper.cpp
- src/PythonWrapper.h
feat(producer) add specified order producer
XX
XXXX
> feat(producer) add specified order producer

- .travis.yml
- README.md
- setup.py
Pull the docker image from the official docker hub repo.
XX
XXXX
> Pull the docker image from the official docker hub repo.

- samples/producer.py
- tests/test_producer.py
> test(producer) improve the transaction unit test stability

- rocketmq/client.py
- rocketmq/ffi.py
- tests/test_producer.py
remove deprecated APIs
remove async send message function.
> feat(producer): can not support async send anymore

- tests/conftest.py
- tests/test_consumer.py
- tests/test_producer.py
Polish tests. 
Send common messages using non-orderly producer.
> chore(tests): polish tests

- tests/test_consumer.py
> chore(tests) adapt to the ons cpp core

- README.md
- setup.py
docs(readme) fix the pypi link to rocketmq-client-python
XX
XXXX
> docs(readme) fix the pypi link to rocketmq-client-python

- .bumpversion.cfg
- MANIFEST.in
- README.md
- manylinux.sh
- rocketmq/client.py
- rocketmq/exceptions.py
- samples/consumer.py
- samples/producer.py
- setup.py
- tests/conftest.py
- tests/test_consumer.py
- tests/test_producer.py
> style(client) polish code style

- .travis.yml
#73 fix(travisci): update rocketmq download link to apache archive server
> fix(travisci): update rocketmq download link to apache archive server

- README.md
close #77
[ISSUE #77 ]feat(doc): update cpp library install methods.
feat(doc): update cpp library install methods.
> feat(doc): update cpp library install methods.

- README.md
Repair consumer usage in 'README.md'
> [ISSUE #88]Sample Callback should return ConsumeStatus

- rocketmq/client.py
#96 possible memory leak
fix memleak  for message created by cpp library not released in class Message
[ISSUE #96]
it happens in our production environment，the memory kepped increasing during the app running, it may up to 10Gb after running several days
when fixed by this, it shows:
```
● qos_collector.service - qos_collector
Loaded: loaded (/etc/systemd/system/qos_collector.service; enabled; vendor preset: disabled)
Active: active (running) since Fri 2020-10-09 09:18:24 CST; 3 days ago
Main PID: 31166 (python2.7)
Memory: 143.6M
CGroup: /system.slice/qos_collector.service
└─31166 /usr/bin/python /data/home/qos/opt/qos_collector/src/app.py --dev
```
> [ISSUE #96] Fix the memory leak in Message

- dev-requirements.txt
- tests/test_producer.py
Try to reproduce and fix #101 
XX
XXXX
> Add a multi-thread producer test case

- rocketmq/client.py
- rocketmq/ffi.py
support message trace in python client
XX
XXXX
> support trace
